version: "3.3"
services:
  engine:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./project/:/workspace"
    ports:
      - "8888:8888"
    shm_size: '32gb'
    command: tail -f /dev/null
